### ISSUE TITLE
Build error from Visual Studio 2019

### ISSUE THREAD

**Issue by SurfingDude** [amullarney/EAS-E#1]
Got one build error on /VSprojects/easeApp2/easeApp2.sln  
    Using Visual Studio Community 2019 -- 16.3.4
    With C++ v14.22 MFC for v142
	File comlib.cpp gets 4 build errors - lines 39 and 41
	each line earns two messages
	   no instance of overloaded function "wcstombs_t" matches the argument list
	   cannot convert argument1 from 'unsigned int *' to 'size_t *'
All the other .sln files build cleanly
This could be due to a Microsoft change between VS 2017 and 2019

**Comment by amullarney** [comment]
I will take a look.. comlib is only for networking the persistence server.. you won't need that for a while yet, I think.- and I get to see an issue in GitHub

    On Friday, October 11, 2019, 2:45:59 PM PDT, Glen Johnson <notifications@github.com> wrote:  
 
 
Got one build error on /VSprojects/easeApp2/easeApp2.sln
Using Visual Studio Community 2019 -- 16.3.4
With C++ v14.22 MFC for v142
File comlib.cpp gets 4 build errors - lines 39 and 41
each line earns two messages
no instance of overloaded function "wcstombs_t" matches the argument list
cannot convert argument1 from 'unsigned int *' to 'size_t *'
All the other .sln files build cleanly
This could be due to a Microsoft change between VS 2017 and 2019

**Comment by amullarney** [comment]
Not replicated when I built with VS2019 - nevertheless, made a slightly 'cleaner' edit to comlib.cpp.  Glen now has clean build.
